//Acording to the select and file names
const sizes = {
  //Name (width, height)
  "Circular Chica": [4, 4],
  "Circular Grande": [6, 6],
  "Desodorante Chica": [3, 4],
  "Desodorante Grande": [4, 5.5],
  Jabones: [6, 4],
  Liquidos: [5, 7],
  "Shampoo Ruda": [5, 7.5],
};

const ingredients = {
  Ninguno: "",
  Romero: "90C165",
  "Cola de Caballo": "4F882A",
  Cactus: "99d3d0",
  "Cascara Nuez": "f0c07a",
  Espinosilla: "e82935",
  Ruda: "eee705",
  Eucalipto: "738c6f",
  Manzanilla: "e88e19",
  Miel: "fdc62c",
  "Aceite Coco": "dbd8df",
  "Manteca Karite": "b5a58d",
  "Flor Hibisco": "c2250d",
  "Carbon Activado": "3a3b40",
  Citricos: "ebdb14",
  Avena: "f5e6c3",
  Tepezcohuite: "66965e",
  Marrubio: "92a892",
  Arroz: "f0e8dc",
  Café: "2e1216",
  Bicarbonato: "ed7015",
  "Leche magnesia": "3071a4",
  Alumbre: "988f9d",
  Cuachalalate: "c59668",
  Calendula: "f3a002",
};

const barcodeNames = [
  "Acondicionador Solido.png",
  "Bolsa De Arnica Seca.png",
  "Bolsa De Espinosilla Seca.png",
  "Bolsa De Marrubio Seca.png",
  "Cepillo De Bambu.png",
  "Crema Arnica, Calendula.png",
  "Crema Chica numero 8 Manzanilla, Miel.png",
  "Crema Grande numero 10 Manzanilla, Miel.png",
  "Crema Tepezcohuite, Cuachalalte.png",
  "Desodorante Alumbre.png",
  "Desodorante Leche Magnesia.png",
  "Desodorante Solido Coco, Karite, Bicarbonato.png",
  "Gel Antibacterial Manos Arnica 250ml Con Dispensador.png",
  "Gel Antibacterial Manos Arnica Con Dispensador 1L.png",
  "Gel Antibacterial Manos Arnica Con Dispensador 300ml.png",
  "Gel Antibacterial Manos Arnica Sin Dispensador 250ml.png",
  "Gel Antibacterial Manos Arnica Sin Dispensador 500ml.png",
  "Gel Arnica.png",
  "Jabon  Solido Cafe Miel.png",
  "Jabon De Tepezcohuite Miel.png",
  "Jabon Liquido Antibacterial 250 Ml Con Arnica.png",
  "Jabon Liquido Antibacterial Con Arnica 500 Ml Sin Dispensador.png",
  "Jabon Liquido Antibacterial Con Dispensador 500 Ml.png",
  "Jabon Solido Arnica Miel.png",
  "Jabon Solido Arroz Y miel.png",
  "Jabon Solido Avena Miel.png",
  "Jabon Solido De Marrubio Azomiate.png",
  "Jabon Solido De Romero Miel.png",
  "Jabon Solido De Rosa De Castilla.png",
  "JABON SOLIDO DE TEPEZCOHIUTE Y CUACAHALALATE.png",
  "Jabon Solido Espinosilla y Arnica Higiene Intima.png",
  "Jabon Solido Manzanilla Y Miel.png",
  "Pomada Arnica.png",
  "Shampoo Liquido Anticaida Romero, Espinosilla 250ml.png",
  "Shampoo Liquido Anticaida Romero, Espinosilla 500ml.png",
  "Shampoo Liquido Antipiojos Ruda 250ml.png",
  "Shampoo Liquido Cascara De Nuez 250ml.png",
  "Shampoo Liquido Cascara De Nuez 500ml.png",
  "Shampoo Liquido Manzanilla, Miel 250ml.png",
  "Shampoo Liquido Manzanilla, Miel 500ml.png",
  "Shampoo Liquido Romero, Cola De Caballo 250ml.png",
  "Shampoo Liquido Romero, Cola De Caballo 500ml.png",
  "Shampoo Solido Carbon Activado, Citricos.png",
  "Shampoo Solido Flor De Hibisco, Citricos.png",
  "Shampoo Solido Romero.png",
];
